force-app/main/default/objects/Comparable__c/Comparable__c.object-meta.xml
<CustomObject>
    <label>Comparable</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Comparable #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comparables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comparable__c/fields/Base_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Base_Opportunity__c</fullName>
    <label>Base Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Comparables</relationshipLabel>
    <relationshipName>ComparablesBase</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comparable__c/fields/Comparable_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Comparable_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comparable Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Comparables (Comparable Opportunity)</relationshipLabel>
    <relationshipName>ComparablesComparable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ComparableOppsTest.cls
//Created on 2022.07.13

@isTest
public class ComparableOppsTest {
        @isTest static void noComparableOpps() {
                //Create records
                Account acc     = new Account();
                acc.Name        = 'New Acc';
                acc.Industry    = 'Hospitality';
                insert acc;

                Opportunity opp = new Opportunity();
                opp.Name        = 'New Acc Opp';
                opp.AccountId   = acc.Id;
                opp.Amount      = 100;
                opp.StageName   = 'Prospecting';
                opp.CloseDate   = Date.today();
                insert opp;

                //Query latest values
                List<Comparable__c> comparables = [SELECT Id
                                                     FROM Comparable__c
                                                    WHERE Base_Opportunity__c= :opp.Id];
                //Assert
                System.assertEquals(0, comparables.size());
        }

        @isTest static void multipleComparableOpps() {
                //Create records: we need two comparable opps
                Account acc  = new Account();
                acc.Name     = 'New Acc';
                acc.Industry = 'Hospitality';
                insert acc;

                List<Opportunity> comparableOpps = new List<Opportunity>();
                Opportunity comp1 = new Opportunity();
                comp1.Name        = 'New Acc Opp';
                comp1.AccountId   = acc.Id;
                comp1.Amount      = 105;
                comp1.StageName   = 'Closed Won';
                comp1.CloseDate   = Date.today().addDays(-1);
                comparableOpps.add(comp1);

                Opportunity comp2 = new Opportunity();
                comp2.Name        = 'New Acc Opp';
                comp2.AccountId   = acc.Id;
                comp2.Amount      = 95;
                comp2.StageName   = 'Closed Won';
                comp2.CloseDate   = Date.today().addDays(-100);
                comparableOpps.add(comp2);
                insert comparableOpps;

                Opportunity baseOpp = new Opportunity();
                baseOpp.Name        = 'New Acc Opp';
                baseOpp.AccountId   = acc.Id;
                baseOpp.Amount      = 100;
                baseOpp.StageName   = 'Prospecting';
                baseOpp.CloseDate   = Date.today();
                insert baseOpp;

                List<Comparable__c> comparables = [SELECT Id,
                                                          Comparable_Opportunity__c
                                                     FROM Comparable__c
                                                    WHERE Base_Opportunity__c = :baseOpp.Id
                                                 ORDER BY Comparable_Opportunity__r.CloseDate DESC];

                System.assertEquals(comp1.Id, comparables.get(0).Comparable_Opportunity__c);       
                System.assertEquals(comp2.Id, comparables.get(1).Comparable_Opportunity__c);          
        }
}